### ISSUE TITLE
HTTP request with jwt

### ISSUE THREAD

**Issue by vlaude** [miage-lille/miage-auth#1]
Bonjour Monsieur,

Je n'arrive pas à accéder aux ressources protégées de mon API, j'ai ajouté un header _Authorization_ avec mon token (de plusieurs façons différentes) mais mon serveur m'affiche toujours un token vide ...
J'utilise _Insomnia_, auriez-vous un exemple de header http avec un token svp ? Merci !

Et aussi, quel encodage utiliser pour afficher les icons dans les logs ? Je ne les vois **pas** avec
LANG=fr_FR.UTF-8
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_ALL=

Vincent Laude

**Comment by oteku** [comment]
Vous devez avoir les headers suivants pour Insomnia (ou Postman)
- Content-Type = application/json
- Authorization = JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6ImU4NTRlMWZmLTJhOTctNDkyOC04NjY0LWRlNWJiZTQ5YzVmMSJ9.rpOnvjv0fJO6rioFM2fpXIb6D-kacP2JmHShrLFSDvg
(à remplacer par votre token mais préfixé par `JWT `)

Pour les icones dans la console c'est de l'unicode, c'est votre émulateur de terminal qui ne doit pas les prendre en compte.
