### ISSUE TITLE
Création de la table "Group" : Metadata

### ISSUE THREAD

**Issue by Debaerdm** [miage-lille/miage-auth#3]
Bonjour,

Thomas et moi travaillons actuellement sur la création de la table Group, et on voulait savoir ce qu'il pouvait y avoir dans le metadata ? Possède t'il le owner (User) ou/et la liste des membres du groupes (Liste de User) ? 

Merci d'avance !

**Comment by oteku** [comment]
Non vous avez un SGBDR les exemples que vous citez se modelise bien avec des clés étrangère ou des tables d'association.

Quand on parle de métadonnées, on parle de données d'anotations qui servent à donner des informations complémentaires. Ces données sont typiquement variables en nombre, en type ou en contenu en fonction de la donnée d'une ligne de la table. Il s'agit d'un problème complexe à traiter avec un SGBDR classique (on peut y arriver avec un méta modèle mais c'est une solution complexe et coûteuse) car non modélisable à priori... Typiquement les bases NoSQL de type indexe ou documents résolvent bien ces problématiques et très simplement.
Ça tombe bien PostgreSQL permet de créer des colonnes documents json.
En réalité PostgreSQL est multi paradigme SGBDR et documents.

Dans notre cas ça peut être : la thématique du groupe, une liste de mot clé qui décrivent un groupe, l'URL de la charte d'utilisation s'il y en a une, un texte de bienvenue, ...
